name: ubuntu-ci
on: [push, pull_request]

jobs:
  build:
    name: Build on ubuntu-18.04:ghc-${{ matrix.ghc }}:cabal-${{ matrix.cabal }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ['8.6', '8.8', '8.10']
        cabal: ['2.4', '3.2']
        exclude:
          # GHC 8.8+ only works with cabal v3+
          - ghc: 8.8
            cabal: 2.4
          - ghc: 8.10
            cabal: 2.4
    env:
        CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: cabal v2-update
      - run: cabal v2-freeze $CONFIG && cat cabal.project.freeze

      - run: "cabal update && cabal v2-build $CONFIG"
      - run: cabal v2-configure --enable-test

      - if: "matrix.cabal < '3'"
        run: cabal v2-test
      - if: "matrix.cabal >= '3'"
        run: cabal v2-test --test-show-details=direct

      - run: cabal check
      - run: cabal v2-haddock
      - run: cabal v2-sdist
